project:
  type: website

website:
  title: "iammees"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/iammees
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



